#!/bin/bash

lupdate -no-ui-lines -no-obsolete  -disable-heuristic sametext -disable-heuristic similartext -disable-heuristic number *.pro

cd ../translations

find . -iname "*.ts" -exec sed -i "/^        <location filename=/d" '{}' \;
